#!/usr/bin/env php
<?php

// Version PHP 8.3
if (PHP_VERSION_ID >= 80300) {

    require './bootstrap.php';

    \Flytachi\Winter\Kernel\Actuator::use(
        new \Flytachi\Winter\Console\Core($argv)
    );

} else {
    echo "\033[33m"." Please use PHP version 8.3 or higher.\n";
    echo "\033[34m"." Current PHP version => " . PHP_VERSION . "\n";
}